 This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: whoami && id
      - run: sudo apt-get update -y
