name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # Install git ftp and make it executable
      - run: mkdir ~/bin && curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > ~/bin/git-ftp
      - run: chmod +x ~/bin/git-ftp
      - run: mkdir gittest2020 && cd gittest2020 && git init && git status  && git fetch

      - run: git config git-ftp.url "ftp://13.56.209.238:21/"
      - run: git config git-ftp.user "upload" && git config git-ftp.password "Galaxy@123"
      # Use git-ftp to copy all the files to the server, while keeping the connection
      - run: git ftp init
