name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: whoami && id
      - run: sudo apt-get update -y
      # Install git ftp and make it executable
      - run: mkdir ~/bin && curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > ~/bin/git-ftp
      - run: chmod +x ~/bin/git-ftp
      - run: git clone https://github.com/jakshaygalaxy2020/gittest2020.git 
      - run: cd gittest2020 && pwd && ls -la && git status

      - run: git config --global user.email "akshay.jain@galaxyweblinks.in"
      - run: git config --global user.name "jakshaygalaxy2020"
      # Use git-ftp to copy all the files to the server, while keeping the connection
      - run: git ftp init --user upload --passwd "Galaxy@123" "ftp://13.56.209.238/"
