# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    runs-on: ruby:2.5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: whoami && id
      - run: sudo apt-get update -y &&
      # Install git ftp and make it executable
      - run: sudo curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > /usr/bin/git-ftp
      - run: sudo chmod +x /usr/bin/git-ftp

      - run: git config --global user.email "gituser@github.com"
      - run: git config --global user.name "gituser"
      # Use git-ftp to copy all the files to the server, while keeping the connection
      - run: git ftp push --user frpuser --passwd ftp-user-password "ftp://SERVER-IP-ADDRESS:22/home/user/public_html" -f || exit_code=$? if [[ $exit_code -ne 0 ]]; then git ftp init --user frpuser --passwd ftp-user-password "ftp://SERVER-IP-ADDRESS:22/home/user/public_html" -f; fi;
      - run: echo "Pushed to DEV Server"
